# Generated by Django 6.0 on 2025-12-26 14:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_organizacji', models.CharField(max_length=100)),
                ('nr_telefonu', models.CharField(help_text='Podaj numer telefonu składający się tylko z 9 cyfr', max_length=9, validators=[django.core.validators.RegexValidator(message='Numer telefonu musi składać się z dokładnie 9 cyfr.', regex='^\\d{9}$')])),
                ('nip', models.CharField(max_length=10, unique=True)),
                ('weryfikacja', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nr_telefonu', models.CharField(help_text='Podaj numer telefonu składający się tylko z 9 cyfr', max_length=9, validators=[django.core.validators.RegexValidator(message='Numer telefonu musi składać się z dokładnie 9 cyfr.', regex='^\\d{9}$')])),
                ('wiek', models.PositiveSmallIntegerField(blank=True, help_text='Wiek', null=True)),
                ('rola', models.CharField(choices=[('wolontariusz', 'Wolontariusz'), ('koordynator', 'Koordynator'), ('organizacja', 'Organizacja')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, related_name='uzytkownik_set', related_query_name='uzytkownik', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='uzytkownik_set', related_query_name='uzytkownik', to='auth.permission', verbose_name='user permissions')),
                ('organizacja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uzytkownicy', to='wolontariat.organizacja')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_projektu', models.CharField(max_length=100)),
                ('opis_projektu', models.TextField()),
                ('organizacja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projekty', to='wolontariat.organizacja')),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul_oferty', models.CharField(max_length=100)),
                ('lokalizacja', models.CharField(max_length=100)),
                ('data', models.DateField(blank=True, null=True)),
                ('data_wyslania', models.DateTimeField(default=django.utils.timezone.now)),
                ('czy_ukonczone', models.BooleanField(default=False)),
                ('tematyka', models.CharField(blank=True, max_length=100)),
                ('czas_trwania', models.CharField(blank=True, max_length=50)),
                ('wymagania', models.TextField(blank=True)),
                ('wolontariusz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oferty', to=settings.AUTH_USER_MODEL)),
                ('organizacja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oferty', to='wolontariat.organizacja')),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oferty', to='wolontariat.projekt')),
            ],
        ),
        migrations.CreateModel(
            name='Wiadomosc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresc', models.TextField()),
                ('data_wyslania', models.DateTimeField(auto_now_add=True)),
                ('nadawca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wyslane_wiadomosci', to=settings.AUTH_USER_MODEL)),
                ('odbiorca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otrzymane_wiadomosci', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recenzja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.PositiveSmallIntegerField()),
                ('komentarz', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('oferta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recenzje', to='wolontariat.oferta')),
                ('organizacja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recenzje', to='wolontariat.organizacja')),
                ('wolontariusz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recenzje', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('oferta', 'organizacja')},
            },
        ),
        migrations.CreateModel(
            name='Zlecenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czy_ukonczone', models.BooleanField(default=False)),
                ('czy_potwierdzone', models.BooleanField(default=False)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zlecenia', to='wolontariat.oferta')),
                ('wolontariusz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zlecenia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('oferta', 'wolontariusz')},
            },
        ),
    ]
